---
name: lint
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**.ino'
    branches:
      - main
  pull_request:
    paths:
      - '**.ino'
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
