---
name: lint
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**.ino'
    branches:
      - main
  pull_request:
    paths:
      - '**.ino'
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'arduino-lint'
        uses: arduino/arduino-lint-action@v1
      - name: 'yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: ./.yamllint
