---
name: test
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'solar-battery-charger.ino'
    branches:
      - main
  pull_request:
    paths:
      - 'solar-battery-charger.ino'
    branches:
      - main
  workflow_dispatch:

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["arduino:samd", "arduino:avr"]
        include:
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:huzzah"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
          arduino-cli lib install ThingSpeak "Adafruit SH110X" "Adafruit GFX Library"
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} .
