---
name: test
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**.ino'
    branches:
      - main
  pull_request:
    paths:
      - '**.ino'
    branches:
      - main
  workflow_dispatch:

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: 
          - "esp8266:esp8266"
        include:
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:huzzah"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Setup go-task
        uses: 'lukeshay/setup-task@v1'
      - name: Install platform
        run: |
          task secrets SSID=MySSID PASS=MyPassword CH_ID=0000000 WRITE_APIKEY=XYZ USER_APIKEY=ABC
          task bootstrap
      - name: Compile Sketch
        run: arduino-cli compile -b ${{ matrix.fqbn }} .
