---
name: test
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'solar-battery-charger.ino'
    branches:
      - main
  pull_request:
    paths:
      - 'solar-battery-charger.ino'
    branches:
      - main
  workflow_dispatch:

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["esp8266:esp8266"]
        include:
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:huzzah"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          touch secrets.h
          echo "#define SECRET_SSID \"MySSID\"" > secrets.h
          echo "#define SECRET_PASS \"MyPass\"" >> secrets.h
          echo "#define SECRET_CH_ID 0000000" >> secrets.h
          echo "#define SECRET_WRITE_APIKEY \"123\"" >> secrets.h
          echo "#define SECRET_HOSTNAME \"Feather\"" >> secrets.h
          echo "#define SECRET_USER_APIKEY \"XYZ\"" >> secrets.h
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
          arduino-cli lib install ThingSpeak "Adafruit SH110X" "Adafruit GFX Library" Time Timezone
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} .
